// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwfonispezljglrclia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod2ZvbmlzcGV6bGpnbHJjbGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjMzNTYsImV4cCI6MjA1OTEzOTM1Nn0.tLXi1DUINNeKyLEA0lDKF8vGiTR8AXxliKOZRVmtW6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);